name: publish-webpage

on:
  push:
    branches:
      - main

jobs:
  publish-webpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Setup Hexo
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:|
          mkdir -p ~/.ssh/
          echo "$GITHUB_TOKEN$" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Deploy page
        run:|
          hexo clean
          hexo deploy
