name: publish-webpage

on:
  push:
    branches:
      - main

jobs:
  publish-webpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Build and Deploy
        uses: renzhaosy/hexo-deploy-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REPOSITORY: jasonren0403/blog-of-jason # The repository the action should deploy to.
          BRANCH: main  # The branch the action should deploy to.
          PUBLISH_DIR: ./public # The folder the action should deploy.
