name: publish-webpage

on:
  push:
    branches:
      - main

jobs:
  publish-webpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Setup Hexo Dependencies
        run: |
          npm install hexo-cli -g
          npm install
      - name: Setup Deploy Key
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GITHUB_TOKEN$" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Setup Git Information
        run: |
          git config --global user.name 'Jason Ren'
          git config --global user.email '40999116+jasonren0403@users.noreply.github.com'
      - name: Deploy page
        run: |
          hexo clean
          hexo generate
          hexo deploy
