name: publish-webpage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-webpage:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deploy Key Setup 🔑
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Install Hexo cli
        run: |
          npm install hexo-cli -g
          npm install
      - name: Fetch current htmls
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
          path: .deploy_git
      - name: Build Hexo 🔧
        run: |
          hexo clean
          hexo generate
          hexo deploy
