name: publish-webpage

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-webpage:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: main
          repository: jasonren0403/blog-of-jason
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Hexo
        run: |
          npm install hexo-cli -g
          npm ci
      - name: Build Hexo
        run: |
          hexo clean
          export TZ='Asia/Shanghai'
          hexo generate
        shell: bash
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.HEXO_DEPLOY_KEY }}
          branch: gh-pages
          folder: public
          repository-name: jasonren0403/blog-of-jason
          git-config-name: "Jason Ren"
          git-config-email: "40999116+jasonren0403@users.noreply.github.com"
